// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyeqzhiwrymkrebhjvor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5ZXF6aGl3cnlta3JlYmhqdm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2ODI3MTIsImV4cCI6MjA4OTI1ODcxMn0.LH8oy8lYiCUMAT30B7dFOomhqgNahmF6STqVZfjEGcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});