// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vazveivrvfrhxugujfop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhenZlaXZydmZyaHh1Z3VqZm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYxNzc2MjgsImV4cCI6MjEwMTc1MzYyOH0.1ucJnuSkXcIyQAkyoUmj4e6p8p0JIUKcNrajFnzVdeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});